#Start with a base image containing Java runtime
FROM openjdk:21-jdk-slim

#LABEL "org.opencontainers.image.authors"="sabdash" Optional, for now I am not giving this
# Add the application's jar to the image
COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar

# execute the application
ENTRYPOINT ["java","-jar","accounts-0.0.1-SNAPSHOT.jar"]