spring:
  application:
    name: "configserver"
  profiles:
#     active: native
      active: git
  cloud:
    config:
      server:
#         native:
#           #search-locations: "file:///path of file followed by triple slash"
#           search-locations: "classpath:/config"
          git:
            uri: "https://github.com/sabyasachi06/E2EMicroservice-config.git"
            default-label: main
            timeout: 5
            clone-on-start: true
#  rabbitmq:    ------> Not needed anymore, since we are not depending on rabbitmq
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
        
server:
  port: 8071
